### ISSUE TITLE
Stream SQL processing

### ISSUE THREAD

**Issue by xerial** [xerial/sbt-sql#9]
To read large data set, apply(rs:ResultSet) should return stream operator.

**Comment by takezoe** [comment]
I really want this. A case class version would be nice like:
```scala
// Normal version
val results: Seq[Product] = Product.secet(...)

// Stream version
Product.foreach(...) { p: Product =>
  ... 
}
```

**Comment by xerial** [comment]
A tricky part would be closing the JDBC connection properly even when the stream is not fully consumed.

**Comment by xerial** [comment]
Similar problem https://github.com/wvlet/airframe/issues/454

**Comment by takezoe** [comment]
With the generated class by sbt-sql, usercode is responsible for connection management. So, we would be able to use the stream interface as follows:
```scala
implicit conn: Connection = ...
try {
  Product.foreach(...) { p: Product =>
    ... 
  }
} finally {
  conn.close()
}
```
